In [8]:
import pandas as pd
from sqlalchemy import create_engine
engine = create_engine('sqlite:///CryptoDB.db')

In [10]:
pd.read_sql('BTCUSDT',engine)

       symbol                    Time     Price
0     BTCUSDT 2021-12-26 18:21:55.318  50241.32
1     BTCUSDT 2021-12-26 18:21:56.139  50241.32
2     BTCUSDT 2021-12-26 18:21:56.199  50241.32
3     BTCUSDT 2021-12-26 18:21:56.400  50241.32
4     BTCUSDT 2021-12-26 18:21:56.689  50241.33
...       ...                     ...       ...
2197  BTCUSDT 2021-12-26 18:45:30.842  50224.52
2198  BTCUSDT 2021-12-26 18:45:30.842  50224.52
2199  BTCUSDT 2021-12-26 18:45:30.842  50224.52
2200  BTCUSDT 2021-12-26 18:45:31.054  50224.52
2201  BTCUSDT 2021-12-26 18:45:31.054  50224.52

[2202 rows x 3 columns]